name: Check - Git Inspector

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  inspect:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Install python
      run: sudo apt -y install python
    - name: Install gitinspector
      run: | 
        pushd ~ &> /dev/null
        git clone --depth=1 https://github.com/ejwa/gitinspector.git
        cd gitinspector
        echo "export PATH=$(pwd):"'$PATH' >> ~/.profile
        popd &> /dev/null
    - name: Run gitinspector
      run: |
        source ~/.profile
        export PYTHONIOENCODING=utf-8
        gitinspector.py --version
        echo "Running for commit : $GITHUB_SHA"
        echo "============ Git Inspector ==========="
        gitinspector.py -wTHl --format=text -f c,h,md,yml,* -x file:3_implementation/unity -x file:doc .
        gitinspector.py -wTHl --format=html -f c,h,md,yml,* -x file:3_implementation/unity -x file:doc . > ~/result.html
        echo "======================================"
